/**
 * Lazy loading utilities for performance optimization
 * Implements intelligent component and asset lazy loading
 */

import { lazy, ComponentType, LazyExoticComponent } from 'react';

// Configuration for lazy loading thresholds
export const LAZY_LOADING_CONFIG = {
  // Component size threshold in KB for lazy loading
  COMPONENT_SIZE_THRESHOLD: 100,
  
  // Asset size threshold in KB for lazy loading
  ASSET_SIZE_THRESHOLD: 100,
  
  // Intersection observer options for lazy loading
  INTERSECTION_OPTIONS: {
    rootMargin: '50px',
    threshold: 0.1,
  },
  
  // Preload distance for images
  PRELOAD_DISTANCE: '200px',
} as const;

// Component size mapping (in KB) - would be generated by build tools in production
export const COMPONENT_SIZES = {
  'Dashboard': 150,
  'OrderHistory': 120,
  'PaymentFlow': 200,
  'UploadArea': 80,
  'UserProfile': 60,
  'Settings': 90,
  'OrderHistoryTable': 110,
  'PaymentStatusCard': 75,
  'FileUploadZone': 85,
} as const;

/**
 * Determines if a component should be lazy loaded based on its size
 */
export function shouldLazyLoadComponent(componentName: string): boolean {
  const size = COMPONENT_SIZES[componentName as keyof typeof COMPONENT_SIZES] || 50;
  return size > LAZY_LOADING_CONFIG.COMPONENT_SIZE_THRESHOLD;
}

/**
 * Creates a lazy-loaded component with loading fallback
 */
export function createLazyComponent<T extends ComponentType<any>>(
  importFn: () => Promise<{ default: T }>,
  componentName?: string
): LazyExoticComponent<T> {
  return lazy(() => {
    // Add artificial delay in development to simulate loading
    if (process.env.NODE_ENV === 'development' && componentName) {
      const size = COMPONENT_SIZES[componentName as keyof typeof COMPONENT_SIZES] || 50;
      const delay = Math.min(size / 10, 100); // Max 100ms delay
      
      return new Promise(resolve => {
        setTimeout(() => {
          importFn().then(resolve);
        }, delay);
      });
    }
    
    return importFn();
  });
}

/**
 * Lazy loading wrapper for large components
 */
export const LazyComponents = {
  Dashboard: createLazyComponent(
    () => import('@/app/dashboard/page'),
    'Dashboard'
  ),
  
  OrderHistoryTable: createLazyComponent(
    () => import('@/components/order/OrderHistoryTable'),
    'OrderHistoryTable'
  ),
  
  PaymentFlow: createLazyComponent(
    () => import('@/components/payment/PaymentFlow'),
    'PaymentFlow'
  ),
  
  FileUploadZone: createLazyComponent(
    () => import('@/components/upload/FileUploadZone'),
    'FileUploadZone'
  ),
} as const;

/**
 * Asset lazy loading utilities
 */
export class AssetLazyLoader {
  private static observer: IntersectionObserver | null = null;
  private static loadedAssets = new Set<string>();

  /**
   * Initialize the intersection observer for lazy loading
   */
  static initialize() {
    if (typeof window === 'undefined' || this.observer) return;

    this.observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            const element = entry.target as HTMLElement;
            this.loadAsset(element);
            this.observer?.unobserve(element);
          }
        });
      },
      LAZY_LOADING_CONFIG.INTERSECTION_OPTIONS
    );
  }

  /**
   * Observe an element for lazy loading
   */
  static observe(element: HTMLElement) {
    if (!this.observer) this.initialize();
    this.observer?.observe(element);
  }

  /**
   * Load an asset when it becomes visible
   */
  private static loadAsset(element: HTMLElement) {
    const src = element.dataset.src;
    if (!src || this.loadedAssets.has(src)) return;

    if (element.tagName === 'IMG') {
      const img = element as HTMLImageElement;
      img.src = src;
      img.removeAttribute('data-src');
    } else if (element.tagName === 'VIDEO') {
      const video = element as HTMLVideoElement;
      video.src = src;
      video.removeAttribute('data-src');
    }

    this.loadedAssets.add(src);
  }

  /**
   * Preload critical assets
   */
  static preloadAssets(urls: string[]) {
    urls.forEach(url => {
      if (this.loadedAssets.has(url)) return;

      const link = document.createElement('link');
      link.rel = 'preload';
      
      if (url.match(/\.(jpg|jpeg|png|webp|gif)$/i)) {
        link.as = 'image';
      } else if (url.match(/\.(mp4|webm|ogg)$/i)) {
        link.as = 'video';
      } else if (url.match(/\.(woff|woff2|ttf|otf)$/i)) {
        link.as = 'font';
        link.crossOrigin = 'anonymous';
      } else {
        link.as = 'fetch';
        link.crossOrigin = 'anonymous';
      }
      
      link.href = url;
      document.head.appendChild(link);
      this.loadedAssets.add(url);
    });
  }

  /**
   * Clean up the observer
   */
  static cleanup() {
    if (this.observer) {
      this.observer.disconnect();
      this.observer = null;
    }
  }
}

/**
 * Hook for lazy loading images
 */
export function useLazyImage(src: string, options?: { 
  placeholder?: string;
  threshold?: number;
}) {
  const { placeholder = '', threshold = 0.1 } = options || {};
  
  return {
    src: placeholder,
    'data-src': src,
    loading: 'lazy' as const,
    onLoad: (e: React.SyntheticEvent<HTMLImageElement>) => {
      const img = e.currentTarget;
      AssetLazyLoader.observe(img);
    }
  };
}

/**
 * Performance monitoring for lazy loading
 */
export class LazyLoadingMetrics {
  private static metrics = {
    componentsLoaded: 0,
    assetsLoaded: 0,
    totalLoadTime: 0,
    initialBundleSize: 0,
    lazyLoadedSize: 0,
  };

  static recordComponentLoad(componentName: string, loadTime: number) {
    this.metrics.componentsLoaded++;
    this.metrics.totalLoadTime += loadTime;
    
    const size = COMPONENT_SIZES[componentName as keyof typeof COMPONENT_SIZES] || 0;
    this.metrics.lazyLoadedSize += size;
    
    if (process.env.NODE_ENV === 'development') {
      console.log(`Lazy loaded component: ${componentName} (${size}KB) in ${loadTime}ms`);
    }
  }

  static recordAssetLoad(assetUrl: string, loadTime: number) {
    this.metrics.assetsLoaded++;
    this.metrics.totalLoadTime += loadTime;
    
    if (process.env.NODE_ENV === 'development') {
      console.log(`Lazy loaded asset: ${assetUrl} in ${loadTime}ms`);
    }
  }

  static getMetrics() {
    return { ...this.metrics };
  }

  static reset() {
    this.metrics = {
      componentsLoaded: 0,
      assetsLoaded: 0,
      totalLoadTime: 0,
      initialBundleSize: 0,
      lazyLoadedSize: 0,
    };
  }
}

// Initialize lazy loading on client side
if (typeof window !== 'undefined') {
  AssetLazyLoader.initialize();
  
  // Clean up on page unload
  window.addEventListener('beforeunload', () => {
    AssetLazyLoader.cleanup();
  });
}